<?php

$title = 'Delete album';
$url   = $this->url('album', ['action' => 'delete', 'id' => $this->album->getId()]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($this->album->getTitle()) ?>" by
    "<?= $this->escapeHtml($this->album->getArtist()) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int)$this->album->getId() ?>"/>
        <input type="submit" class="btn btn-danger" name="del" value="Yes"/>
        <input type="submit" class="btn btn-success" name="del" value="No"/>
    </div>
</form>
