<?php
$title = 'My blogs';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('blog', ['action' => 'add']) ?>">Add new blog</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th>Creation date</th>
        <th>Modification date</th>
        <th>Album title</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->blogs as $blog) : ?>
        <?php /** @var \Blog\Model\Blog $blog */ ?>
        <tr>
            <td><?= $this->escapeHtml($blog->getTitle()) ?></td>
            <td><?= $this->escapeHtml($blog->getText()) ?></td>
            <td><?= $this->escapeHtml($blog->getCreationDate()->format('d/m/Y')); ?></td>
            <td><?= $this->escapeHtml($blog->getModificationDate() ? $blog->getModificationDate()->format('d/m/Y H:i:s') : ''); ?></td>
            <td><?= $this->escapeHtml($blog->getAlbum() ? $blog->getAlbum()->getTitle() : 'NA'); ?></td>
            <td>
                <a href="<?= $this->url('blog', ['action' => 'edit', 'id' => $blog->getId()]) ?>">Edit</a>
                <a href="<?= $this->url('blog', ['action' => 'delete', 'id' => $blog->getId()]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

